[2022-07-22 15:21:16,670] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Data_Quality_Pipeline.add_upload_date__1 manual__2022-07-22T15:21:04.061278+00:00 [queued]>
[2022-07-22 15:21:16,685] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Data_Quality_Pipeline.add_upload_date__1 manual__2022-07-22T15:21:04.061278+00:00 [queued]>
[2022-07-22 15:21:16,685] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 15:21:16,685] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 15:21:16,686] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 15:21:16,713] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): add_upload_date__1> on 2022-07-22 15:21:04.061278+00:00
[2022-07-22 15:21:16,722] {standard_task_runner.py:52} INFO - Started process 2585 to run task
[2022-07-22 15:21:16,733] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Data_Quality_Pipeline', 'add_upload_date__1', 'manual__2022-07-22T15:21:04.061278+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/localtos3.py', '--cfg-path', '/tmp/tmp4149uf7o', '--error-file', '/tmp/tmp41jg8mhx']
[2022-07-22 15:21:16,738] {standard_task_runner.py:80} INFO - Job 11: Subtask add_upload_date__1
[2022-07-22 15:21:16,862] {task_command.py:371} INFO - Running <TaskInstance: Data_Quality_Pipeline.add_upload_date__1 manual__2022-07-22T15:21:04.061278+00:00 [running]> on host d30608300872
[2022-07-22 15:21:17,052] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Data_Quality_Pipeline
AIRFLOW_CTX_TASK_ID=add_upload_date__1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T15:21:04.061278+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T15:21:04.061278+00:00
[2022-07-22 15:21:17,054] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/localtos3.py", line 32, in add_upload_date
    trip_dict = pd.read_csv(
NameError: name 'pd' is not defined
[2022-07-22 15:21:17,073] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Data_Quality_Pipeline, task_id=add_upload_date__1, execution_date=20220722T152104, start_date=20220722T152116, end_date=20220722T152117
[2022-07-22 15:21:17,093] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task add_upload_date__1 (name 'pd' is not defined; 2585)
[2022-07-22 15:21:17,144] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 15:21:17,276] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
